persist readonly to volume info file
jibudata/seaweedfs pull request #347
Opened 2024-09-01 06:04 UTC by half-life666

# What problem are we solving?

# How are we solving the problem?

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

2024-09-01 15:37 UTC, 27149chen requested changes

2024-09-01 15:37 UTC, 27149chen commented on weed/stats/metrics.go
> +var readOnlyVolumeTypes = [4]string{IsReadOnly, CanDelete, IsDiskSpaceLow}
这里是什么意思？

2024-09-01 15:37 UTC, 27149chen commented on weed/topology/volume_layout.go
> +				glog.V(0).Infof("volume id: %d, size: %d, threshold: %f", info.Id, info.Size, float64(vl.volumeSizeLimit)*VolumeGrowStrategy.Threshold)
这个 log 去掉吧

2024-09-01 15:37 UTC, 27149chen commented on weed/topology/volume_layout.go
> +	glog.V(0).Infof("active volume: %d, high usage volume: %d\n", active, crowded)
high usage 后面为什么不是 high？

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume.go
> +		ReadOnly:         v.volumeInfo.ReadOnly,
这里不用改，不然没lock了

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume.go
> +	volumeInfoLock sync.RWMutex
加了 volumeINfoLock，是不是所有 volumeInfo 的操作都要加锁？

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume.go
> +	glog.Infof("NewVolume complete %s collection:%s id:%d", dirname, collection, id)
这几个 log 去掉吧

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		if !v.IsReadOnly() {
这里加个log说明一下为啥要这样做

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume_loading.go
> +			v.PersistReadOnly(true)
这里是有些临时性错误，所以把这个volume标成了只读，目的是为了防止错误的扩大化。所以只读状态也是临时性的，不能持久化

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume_loading.go
> +			}
这里不用改，应该不是同一层级的设置

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume.go
> +	v.SaveVolumeInfo()
SaveVolumeInfo 是在 volume tier 里面定义的，应该是专门给 tier 用的，在这里调用不知道合不合适

2024-09-01 15:37 UTC, 27149chen commented on weed/storage/volume.go
> +func (v *Volume) PersistReadOnly(readOnly bool) {
SaveVolumeReadOnlyInfo

2024-09-02 01:40 UTC, half-life666 commented on weed/stats/metrics.go
> +var readOnlyVolumeTypes = [4]string{IsReadOnly, CanDelete, IsDiskSpaceLow}
定义的几个metrics

2024-09-02 01:41 UTC, half-life666 commented on weed/topology/volume_layout.go
> +	glog.V(0).Infof("active volume: %d, high usage volume: %d\n", active, crowded)
就没有high，就是crowded；之前的log跟外面实现不一致吧

2024-09-02 03:12 UTC, 27149chen commented on weed/topology/volume_layout.go
> +	glog.V(0).Infof("active volume: %d, high usage volume: %d\n", active, crowded)
high usage volume 也应该改成 crowded usage volume？

2024-09-02 03:26 UTC, half-life666 commented on weed/storage/volume.go
> +	volumeInfoLock sync.RWMutex
其实这里没想好，是不是protect readonly persist就够了，正常情况read in memory的信息是不是不需要？

2024-09-02 03:33 UTC, half-life666 commented on weed/storage/volume.go
> +	v.SaveVolumeInfo()
都是volume的方法，之前只有volume tier会用到而已；或者挪到volume.go里

2024-09-02 03:34 UTC, half-life666 commented on weed/storage/volume.go
> +func (v *Volume) PersistReadOnly(readOnly bool) {
PersistReadOnly也很精确啊

2024-09-02 04:00 UTC, half-life666 commented on weed/storage/volume.go
> +	return v.volumeInfo.ReadOnly
isDiskSpaceLow看代码逻辑，如果一个volume server的disk low，add volume时候就不会再找这个volume server了，那其实是一个volume server单位的，跟每个volume其实关系不大；或者说，是不是isDiskSpaceLow到一定程度了，sw应该把所有的volume都自己mark 一遍readonly？

2024-09-03 02:10 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		if !v.IsReadOnly() {
这个？

2024-09-03 02:23 UTC, 27149chen commented on weed/storage/volume_loading.go
> +				glog.V(0).Infof("volumeDataIntegrityChecking failed %v", err)
这里出错不 mark readonly 了？这个风险比较高

2024-09-03 02:23 UTC, 27149chen commented on weed/storage/volume_loading.go
> -			v.noWriteOrDelete = true
这里为什么删了？

2024-09-03 02:23 UTC, 27149chen commented on weed/storage/volume.go
> +func (v *Volume) PersistReadOnly(readOnly bool) {
你看他有类似命名风格的吗？tier 信息存 vif 也是类似的功能，他也没叫做 persist tier info 之类的。一般保持到内存，缓存之类的可以叫 set xxx 之类，保存到文件，数据库之类的可以叫做 save xxx 或者直接叫做 saveToFile saveToDB 之类的，你看他的方法也叫 SaveVolumeInfo，叫做 PersistReadOnly 显得很突兀

2024-09-03 02:27 UTC, 27149chen commented on weed/storage/volume.go
> +	return v.volumeInfo.ReadOnly
这是临时性的，可用空间是动态变化的，所以每次要用的时候检查一下比较合适，因为它已经在维护isDiskSpaceLow这个参数了，没必要再维护一个 readonly 参数，有点冗余，因为用的时候可以由前者推导出后者。
还有很重要的一点，这是个保护性措施，万一同步不一致等原因导致分配了这个volume，readonly 就能阻止进一步的写入

2024-09-03 02:40 UTC, 27149chen requested changes

2024-09-03 02:40 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		if !v.volumeInfo.ReadOnly {
这里为什么直接用 volumeInfo.ReadOnly？ 这样就没 lock 了

2024-09-03 02:40 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		if v.volumeInfo.ReadOnly {
这里为什么直接用 volumeInfo.ReadOnly？ 这样就没 lock 了

2024-09-03 02:40 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		if v.canDelete {
v.noWriteOrDelete || v.noWriteCanDelete 应该等价于 readOnly， 而不是 canDelete，因为 noWriteOrDelete 是不能 delete

2024-09-03 02:40 UTC, 27149chen commented on weed/storage/volume_loading.go
> +	glog.V(0).Info("loaded volume", v.FileName(".dat"))
Infof

2024-09-03 04:43 UTC, half-life666 commented on weed/storage/volume.go
> +	return v.volumeInfo.ReadOnly
isDiskSpaceLow目前用法没有变

2024-09-03 04:50 UTC, half-life666 commented on weed/storage/volume_loading.go
> +		if !v.IsReadOnly() {
这个不太好讲，就是我们这次改这个原因嘛，本来有remote file也是readonly的，只不过我们分开了premig和stub，这期间又有可能sw重启，这个我在issue里面都讲了

2024-09-03 04:52 UTC, half-life666 commented on weed/storage/volume.go
> +func (v *Volume) PersistReadOnly(readOnly bool) {
那现在PersistReadOnly有啥问题吗？命名这个应该是一个有一些灵活度的事情，只要能理解是干嘛，没有写的很离谱，比如全小写，全大写之类，是不是就可以了

2024-09-03 04:56 UTC, half-life666 commented on weed/storage/volume_loading.go
> +		if !v.volumeInfo.ReadOnly {
这里不能用volumeInfo.ReadOnly()，volumeInfo.ReadOnly会检查isLow那个，还没初始化；另外lock我也删了，觉得没啥必要

2024-09-03 06:59 UTC, 27149chen requested changes

2024-09-03 06:59 UTC, 27149chen commented on weed/storage/volume.go
> +	volumeInfoLock sync.RWMutex
volume 这个东西，作者是把它作为缓存用的，在初始化中load 进来之后，一直在使用它的变量和方法，这种做法其实很危险，理论上所有读写变量的操作都应该加锁，除非某个值在初始化之后一直不会变。因为 struct 是并发不安全的。

2024-09-03 06:59 UTC, 27149chen commented on weed/storage/volume.go
> +	canDeleteLock      sync.RWMutex
这里你是把  canDeleteLock 和 volumeInfoLock 都去掉了？

2024-09-03 06:59 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		if !v.IsReadOnly() {
如果要 pr 出去，这里还是得加点log，不然这里调这个感觉比较奇怪。其实也好解释，就是确保 remote 是 readonly 的，万一有异常，或者用户把它改成了 wraitable，启动的时候会改回来

2024-09-03 06:59 UTC, 27149chen commented on weed/storage/volume_loading.go
> -			v.noWriteOrDelete = true
这里之前comment里面说了，这不是同一层级的设置，这里是一个临时性的 readonly=true +canDelete=false，不能持久化

2024-09-03 06:59 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		if v.volumeInfo.ReadOnly {
noWriteOrDelete 应该等价于 readonly=true +canDelete=false

2024-09-03 06:59 UTC, 27149chen commented on weed/storage/volume_loading.go
> +				glog.V(0).Infof("volumeDataIntegrityChecking failed %v", err)
这个前面也解释了，不能持久化，因为可能是一些临时性错误，下次重启它可能就好了，这样这个volume 需要能继续写

2024-09-04 14:58 UTC, closed without merging