Persist readonly
jibudata/seaweedfs pull request #350
Opened 2024-09-04 14:20 UTC by half-life666

# What problem are we solving?

# How are we solving the problem?

# How is the PR tested?

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

2024-09-04 15:56 UTC, 27149chen requested changes

2024-09-04 15:56 UTC, 27149chen commented on weed/storage/store.go
> +	v.PersistReadOnly(true)
把这行放到unlock之前，后面其他地方也一样

2024-09-04 15:56 UTC, 27149chen commented on weed/storage/volume_loading.go
> +			}
这一段去掉，另一个pr里面有了

2024-09-04 15:56 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		// this covers the case where the volume is marked as read-only and has no remote file
这里不用判断has remote file，判断了反而不好理解了。
这里的作用就是把之前持久化下来的状态load到内存中而已，至于remote，下面那几行会修正它的值的

2024-09-05 01:20 UTC, merged

2024-09-05 03:03 UTC, half-life666 commented on weed/storage/volume_loading.go
> +			}
这个分支就是基于上一个pr的分支，所以另一个不进也没关系？

2024-09-05 03:05 UTC, half-life666 commented on weed/storage/volume_loading.go
> +		// this covers the case where the volume is marked as read-only and has no remote file
这里其实逻辑上是没问题的

2024-09-05 04:05 UTC, half-life666 commented on weed/storage/store.go
> +	v.PersistReadOnly(true)
这个我改了，rebase了下，直接在3.72-udm了

2024-09-05 04:21 UTC, 27149chen commented on weed/storage/volume_loading.go
> +			}
你要 pr 到社区，难道还手动在搞一次？肯定是 cherry-pick 啊，那每个 pr 里面就别包含不相干的

2024-09-05 04:23 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		// this covers the case where the volume is marked as read-only and has no remote file
逻辑上绕来绕去可能最终是一样，但这里是把简单问题复杂化了。你持久化的目的，就是为了重启的时候把状态load回来，加一堆判断，反而不容易理解

2024-09-05 04:24 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		// this covers the case where the volume is marked as read-only and has no remote file
就算退一步，加和不加都可以，那为啥要加这个判断

2024-09-05 04:31 UTC, half-life666 commented on weed/storage/volume_loading.go
> +			}
这里有两个commit，cherry pick不是很容易？

2024-09-05 04:32 UTC, half-life666 commented on weed/storage/volume_loading.go
> +		// this covers the case where the volume is marked as read-only and has no remote file
有这个判断才是最清楚最精确的，因为只有这一种情况没有cover，补上就好了

2024-09-05 05:52 UTC, 27149chen commented on weed/storage/volume_loading.go
> +			}
你merge完就变成一个了，feature 分支会被删掉的，要么你现在就 pr 出去

2024-09-05 06:00 UTC, 27149chen commented on weed/storage/volume_loading.go
> +		// this covers the case where the volume is marked as read-only and has no remote file
这里不是 if esle 这样的分支流程，没必要选最清楚最精确的。HasRemoteFile 在后面自己的分支里面会处理。这里的唯一目的就是把之前持久化下来的状态load到内存中而已。从这个函数开头到这两行为止，都是在处理通用场景，这里也没有理由把一些特殊情况给排除掉，因为这里 load 的是初始值。后面 if HasRemoteFile 这个分支才是处理这种特殊情况的具体逻辑，这里会把初始值做一些调整。你看后面也有类似的处理，去修正这个初始值。总结就是先一般后特殊